enum ERR {
    ERR_INVALID_KEY_TYPE = 1,
    ERR_INVALID_KEY_VAL_TYPE,
    ERR_INVALID_CMD_VAL_TYPE,
    ERR_INVALID_PWD_VAL_TYPE,
    ERR_UNEXPECTED_MSG
};

enum MSGKEY {
    MSGKEY_ID_UINT = 1,
    MSGKEY_CMD_UINT,
    MSGKEY_PWD_STR,
};

enum CMD {
    CMD_GIT_STATUS = 1,
};
